apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJiM0psYzJocllXNWxkRHBuYUhCZlpFWnFSazB5VW5oSFowb3lhalZPVWpkd2JtTjBlV1pPT1c1NmFEbGFNbU53V2twWSIKICAgICAgICB9CiAgICB9LAogICAgImNyZWRIZWxwZXJzIjogewogICAgICAgICJjb250YWluZXItcmVnaXN0cnkuY2xvdWQueWFuZGV4Lm5ldCI6ICJ5YyIsCiAgICAgICAgImNyLmNsb3VkLnlhbmRleC5uZXQiOiAieWMiLAogICAgICAgICJjci55YW5kZXgiOiAieWMiCiAgICB9LAogICAgImNyZWRzU3RvcmUiOiAiZGVza3RvcCIKfQ==
type: kubernetes.io/dockerconfigjson
