apiVersion: apps/v1
kind: Deployment
metadata:
  name: events
  namespace: cinemaabyss
  labels:
    app: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      initContainers:
        - name: create-kafka-topics
          image: wurstmeister/kafka:2.13-2.7.0
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Kafka to be ready..."
              while ! /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092 >/dev/null 2>&1; do
                sleep 5
              done
              echo "Kafka is ready. Creating topics..."
              for topic in movie-events user-events payment-events; do
                echo "Creating topic: $topic"
                /opt/kafka/bin/kafka-topics.sh --create \
                  --bootstrap-server kafka:9092 \
                  --topic "$topic" \
                  --partitions 1 \
                  --replication-factor 1 \
                  --if-not-exists
              done
              echo "All topics created."
      containers:
      - name: events-service
        image:  ghcr.io/oreshkanet/ya-architecture-pro-cinemaabyss/events-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: KAFKA_BROKERS
          value: "$(KAFKA_URL)"
        envFrom:
        - configMapRef:
            name: cinemaabyss-config
        - secretRef:
            name: cinemaabyss-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: cinemaabyss
spec:
  selector:
    app: events-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP